// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dnd-themes/ArcaneNeon.tsx": () => import("../components/mockups/dnd-themes/ArcaneNeon.tsx"),
  "./components/mockups/dnd-themes/IronCrimson.tsx": () => import("../components/mockups/dnd-themes/IronCrimson.tsx"),
  "./components/mockups/dnd-themes/MoonlitForest.tsx": () => import("../components/mockups/dnd-themes/MoonlitForest.tsx")
};
